### PR TITLE
Fixed Azure Pipelines run error.

### PR DESCRIPTION
**Pull request by nightwolf3140**
Hopefully this works, someone smarter than me can double check my code. Fixed a bunch of string errors and implicit map key errors.

### CODE REVIEW

**Comment by 12944qwerty** [comment]
We don't use azure pipelines for deployment anymore lol. We use GitHub workflows instead (also, but still less, broken)

**Comment by nightwolf3140** [comment]
> We don't use azure pipelines for deployment anymore lol. We use GitHub workflows instead (also, but still less, broken)

Ah, didnt know. Just saw something broken and gave my best shot at fixing it.

**Comment by nightwolf3140** [comment]
Might want to remove azure cloud satus from the readme.

**Comment by nightwolf3140** [comment]
> We don't use azure pipelines for deployment anymore lol. We use GitHub workflows instead (also, but still less, broken)

**Pull request closed without merging**
